export const UPDATE_PARAMS = 'UPDATE_PARAMS';
export const UPDATE_NOT_AVAILABLE_DATES = 'UPDATE_NOT_AVAILABLE_DATES';
export const UPDATE_HOTEL_DETAIL = 'UPDATE_HOTEL_DETAIL';
export const UPDATE_ROOM_TYPE = 'UPDATE_ROOM_TYPE';
export const UPDATE_VOUCHER = 'UPDATE_VOUCHER';
